extends SceneTree

func _init():
	var lines = []
	lines.append('[gd_scene load_steps=2 format=4]')
	lines.append('')
	lines.append('[ext_resource type="Script" path="res://scripts/ui/TouchLayoutEditor.gd" id="1_script"]')
	lines.append('')
	lines.append('[node name="TouchLayoutEditor" type="CanvasLayer"]')
	lines.append('layer = 101')
	lines.append('script = ExtResource("1_script")')
	lines.append('')
	lines.append('[node name="ColorRect" type="ColorRect" parent="."]')
	lines.append('anchors_preset = 15')
	lines.append('anchor_right = 1.0')
	lines.append('anchor_bottom = 1.0')
	lines.append('color = Color(0, 0, 0, 0.5)')
	lines.append('')
	lines.append('[node name="Label" type="Label" parent="."]')
	lines.append('anchors_preset = 5')
	lines.append('anchor_left = 0.5')
	lines.append('anchor_right = 0.5')
	lines.append('offset_left = -200')
	lines.append('offset_top = 50')
	lines.append('offset_right = 200')
	lines.append('offset_bottom = 100')
	lines.append('text = "Drag buttons to customize layout"')
	lines.append('horizontal_alignment = 1')
	lines.append('vertical_alignment = 1')
	lines.append('theme_override_font_sizes/font_size = 32')
	lines.append('')
	lines.append('[node name="SaveButton" type="Button" parent="."]')
	lines.append('anchors_preset = 1')
	lines.append('anchor_left = 1.0')
	lines.append('offset_left = -200')
	lines.append('offset_top = 50')
	lines.append('offset_right = -50')
	lines.append('offset_bottom = 100')
	lines.append('text = "Save Layout"')
	lines.append('theme_override_font_sizes/font_size = 24')
	lines.append('')
	lines.append('[node name="CancelButton" type="Button" parent="."]')
	lines.append('offset_left = 50')
	lines.append('offset_top = 50')
	lines.append('offset_right = 200')
	lines.append('offset_bottom = 100')
	lines.append('text = "Cancel"')
	lines.append('theme_override_font_sizes/font_size = 24')
	lines.append('')
	lines.append('[node name="ResetButton" type="Button" parent="."]')
	lines.append('anchors_preset = 1')
	lines.append('anchor_left = 1.0')
	lines.append('offset_left = -400')
	lines.append('offset_top = 50')
	lines.append('offset_right = -250')
	lines.append('offset_bottom = 100')
	lines.append('text = "Reset Default"')
	lines.append('theme_override_font_sizes/font_size = 24')
	lines.append('')
	lines.append('[node name="Buttons" type="Control" parent="."]')
	lines.append('anchors_preset = 15')
	lines.append('anchor_right = 1.0')
	lines.append('anchor_bottom = 1.0')
	lines.append('mouse_filter = 2') # IGNORE
	lines.append('')
	
	var file = FileAccess.open("res://scenes/ui/TouchLayoutEditor.tscn", FileAccess.WRITE)
	for line in lines:
		file.store_line(line)
	file.close()
	print("TouchLayoutEditor.tscn created successfully!")
	quit()
