extends SceneTree

func _init():
	var lines = []
	lines.append('[gd_scene load_steps=3 format=4]')
	lines.append('')
	lines.append('[ext_resource type="Script" path="res://scripts/ui/ControlsScreen.gd" id="1_script"]')
	lines.append('[ext_resource type="Texture2D" path="res://assets/ui/menu_background.png" id="2_bg"]')
	lines.append('[ext_resource type="Texture2D" path="res://assets/ui/premium/Frame_tile_31.png" id="3_panel"]')
	lines.append('')
	lines.append('[sub_resource type="StyleBoxTexture" id="StyleBoxTexture_panel"]')
	lines.append('texture = ExtResource("3_panel")')
	lines.append('texture_margin_left = 12.0')
	lines.append('texture_margin_top = 12.0')
	lines.append('texture_margin_right = 12.0')
	lines.append('texture_margin_bottom = 12.0')
	lines.append('')
	lines.append('[node name="ControlsScreen" type="Control"]')
	lines.append('layout_mode = 3')
	lines.append('anchors_preset = 15')
	lines.append('anchor_right = 1.0')
	lines.append('anchor_bottom = 1.0')
	lines.append('grow_horizontal = 2')
	lines.append('grow_vertical = 2')
	lines.append('script = ExtResource("1_script")')
	lines.append('')
	lines.append('[node name="Background" type="TextureRect" parent="."]')
	lines.append('layout_mode = 1')
	lines.append('anchors_preset = 15')
	lines.append('anchor_right = 1.0')
	lines.append('anchor_bottom = 1.0')
	lines.append('grow_horizontal = 2')
	lines.append('grow_vertical = 2')
	lines.append('texture = ExtResource("2_bg")')
	lines.append('expand_mode = 1')
	lines.append('stretch_mode = 6')
	lines.append('')
	lines.append('[node name="CenterPanel" type="Panel" parent="."]')
	lines.append('layout_mode = 1')
	lines.append('anchors_preset = 8')
	lines.append('anchor_left = 0.5')
	lines.append('anchor_top = 0.5')
	lines.append('anchor_right = 0.5')
	lines.append('anchor_bottom = 0.5')
	lines.append('offset_left = -380.0')
	lines.append('offset_top = -360.0')
	lines.append('offset_right = 380.0')
	lines.append('offset_bottom = 360.0')
	lines.append('grow_horizontal = 2')
	lines.append('grow_vertical = 2')
	lines.append('theme_override_styles/panel = SubResource("StyleBoxTexture_panel")')
	lines.append('')
	lines.append('[node name="VBox" type="VBoxContainer" parent="CenterPanel"]')
	lines.append('layout_mode = 1')
	lines.append('anchors_preset = 15')
	lines.append('anchor_right = 1.0')
	lines.append('anchor_bottom = 1.0')
	lines.append('offset_left = 40.0')
	lines.append('offset_top = 30.0')
	lines.append('offset_right = -40.0')
	lines.append('offset_bottom = -20.0')
	lines.append('grow_horizontal = 2')
	lines.append('grow_vertical = 2')
	lines.append('theme_override_constants/separation = 12')
	lines.append('')
	lines.append('[node name="Title" type="Label" parent="CenterPanel/VBox"]')
	lines.append('layout_mode = 2')
	lines.append('theme_override_colors/font_color = Color(1, 0.9, 0.5, 1)')
	lines.append('theme_override_font_sizes/font_size = 48')
	lines.append('text = "Controls"')
	lines.append('horizontal_alignment = 1')
	lines.append('')
	lines.append('[node name="HSpacer" type="Control" parent="CenterPanel/VBox"]')
	lines.append('custom_minimum_size = Vector2(0, 5)')
	lines.append('layout_mode = 2')
	lines.append('')
	lines.append('[node name="TouchLayoutBtn" type="Button" parent="CenterPanel/VBox"]')
	lines.append('layout_mode = 2')
	lines.append('theme_override_font_sizes/font_size = 26')
	lines.append('text = "Customize Touch Layout"')
	lines.append('')
	lines.append('[node name="HSpacer2" type="Control" parent="CenterPanel/VBox"]')
	lines.append('custom_minimum_size = Vector2(0, 5)')
	lines.append('layout_mode = 2')
	lines.append('')
	lines.append('[node name="ScrollContainer" type="ScrollContainer" parent="CenterPanel/VBox"]')
	lines.append('layout_mode = 2')
	lines.append('size_flags_vertical = 3')
	lines.append('')
	lines.append('[node name="KeybindsContainer" type="VBoxContainer" parent="CenterPanel/VBox/ScrollContainer"]')
	lines.append('layout_mode = 2')
	lines.append('size_flags_horizontal = 3')
	lines.append('size_flags_vertical = 3')
	lines.append('theme_override_constants/separation = 10')
	lines.append('')
	lines.append('[node name="Spacer" type="Control" parent="CenterPanel/VBox"]')
	lines.append('layout_mode = 2')
	lines.append('custom_minimum_size = Vector2(0, 10)')
	lines.append('')
	lines.append('[node name="BackBG" type="NinePatchRect" parent="CenterPanel/VBox"]')
	lines.append('custom_minimum_size = Vector2(260, 60)')
	lines.append('layout_mode = 2')
	lines.append('size_flags_horizontal = 4')
	lines.append('texture = ExtResource("3_panel")')
	lines.append('patch_margin_left = 12')
	lines.append('patch_margin_top = 12')
	lines.append('patch_margin_right = 12')
	lines.append('patch_margin_bottom = 12')
	lines.append('')
	lines.append('[node name="BackButton" type="Button" parent="CenterPanel/VBox/BackBG"]')
	lines.append('layout_mode = 1')
	lines.append('anchors_preset = 15')
	lines.append('anchor_right = 1.0')
	lines.append('anchor_bottom = 1.0')
	lines.append('grow_horizontal = 2')
	lines.append('grow_vertical = 2')
	lines.append('theme_override_font_sizes/font_size = 28')
	lines.append('text = "Back"')
	lines.append('flat = true')
	lines.append('')
	lines.append('[node name="RebindOverlay" type="ColorRect" parent="."]')
	lines.append('visible = false')
	lines.append('layout_mode = 1')
	lines.append('anchors_preset = 15')
	lines.append('anchor_right = 1.0')
	lines.append('anchor_bottom = 1.0')
	lines.append('grow_horizontal = 2')
	lines.append('grow_vertical = 2')
	lines.append('color = Color(0, 0, 0, 0.8)')
	lines.append('')
	lines.append('[node name="Label" type="Label" parent="RebindOverlay"]')
	lines.append('layout_mode = 1')
	lines.append('anchors_preset = 15')
	lines.append('anchor_right = 1.0')
	lines.append('anchor_bottom = 1.0')
	lines.append('grow_horizontal = 2')
	lines.append('grow_vertical = 2')
	lines.append('theme_override_font_sizes/font_size = 48')
	lines.append('text = "Press any key..."')
	lines.append('horizontal_alignment = 1')
	lines.append('vertical_alignment = 1')
	lines.append('')
	
	var file = FileAccess.open("res://scenes/ui/ControlsScreen.tscn", FileAccess.WRITE)
	for line in lines:
		file.store_line(line)
	file.close()
	print("ControlsScreen.tscn created successfully!")
	quit()
